### ISSUE TITLE
Add Katunizer Test Flight link

### ISSUE THREAD

**Issue by fyhao** [pluwen/awesome-testflight-link#101]
https://testflight.apple.com/join/cw8X7LeO

**Comment by pluwen** [comment]
Need more introduction information

**Comment by fyhao** [comment]
This apps provide user to cartoonize photo by selecting photo from photo gallery and can be shared to social network.
This apps also provide user to cartoonize photo right from photo apps editing mode.
This apps also provide user to integrate via iOS shortcut action.

**Comment by pluwen** [comment]
done

**Comment by NineXYZ** [comment]
Is your app open source?
Do you have a place to send bugs and suggestions?

**Comment by fyhao** [comment]
Hi, 
Currently my apps is not open source. But you can post bugs and suggestions via following ways that I can receive notifications alert.
- Submit an issue under this repository https://github.com/fyhao/Katunizerapps/issues
- Discord https://discord.com/channels/1062026715695681667/1062026717079818371
- Send to my gmail available in Github profile
