### ISSUE TITLE
Add Pockity

### ISSUE THREAD

**Issue by dezinezync** [pluwen/awesome-testflight-link#103]
**Link**: https://testflight.apple.com/join/hDz4sEi7 
**Platforms**: iOS & iPadOS 

### About
Pockity a simple Expenses and Budget manager for iOS, iPadOS (macOS coming later this year). 

Form a habit of tracking expenses and setup weekly or monthly budget goals. 

Create repeating entries, multiple accounts (to transfer funds between accounts) and sort expenses into categories. 

Get a monthly, quarterly and yearly overview per Ledger. 

A ledger is a neat way to categorize expenses into Personal, Work, Business and similar "books".

**Comment by pluwen** [comment]
done
