### ISSUE TITLE
Add Elytra

### ISSUE THREAD

**Issue by dezinezync** [pluwen/awesome-testflight-link#108]
Link: https://testflight.apple.com/join/PYYu2Cco
Platforms: iOS, iPadOS and macOS 

### About 

Elytra is an RSS-Feed reader and Cloud Service which focuses on Privacy. 

It natively renders all text, images and videos and includes support for Youtube Channels, Mastodon feeds and a lot more. 

It takes privacy very seriously, stripping tracking scripts and images from article content before rendering them. 

It supports a wide array of accessibility features, multi-window support and cross-platform sync.

**Comment by pluwen** [comment]
done
