### ISSUE TITLE
Add QWatch (Quake 1 port for watchOS)

### ISSUE THREAD

**Issue by jankais3r** [pluwen/awesome-testflight-link#114]
Hi,

I have a TestFlight open for my actively developed fork of quake_watch. It's Quake 1 originally ported to watchOS by MyOwnClone. Could you add it to the gaming list?

![QWatch preview](https://user-images.githubusercontent.com/2159464/217112633-35b361d0-186e-4f87-a419-8253aa212e71.png)

TestFlight link: http://testflight.apple.com/join/bJyw9fog

**Comment by pluwen** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/555720/217690475-2171f887-4928-42b3-9eb7-9680764e7b7b.png">

name not match

**Comment by jankais3r** [comment]
Fixed
