### ISSUE TITLE
Working TestFlight of old os?

### ISSUE THREAD

**Issue by SMRZbeats** [pluwen/awesome-testflight-link#123]

**Comment by x13-me** [comment]
What is the issue?

**Comment by SMRZbeats** [comment]
Is there a working version of old os I could use?

**Comment by x13-me** [comment]
No, that is outside the scope of testflight

**Comment by an0nv33r** [comment]
> Is there a working version of old os I could use?

Testflight focuses on testing mobile applications, currently owned by Apple and only offered to developers within the iOS Developer Program. So for OS i don't know what you are talking about.

**Comment by NitroNils** [comment]
FYI This is old OS:

https://www.oldos.dev/

About:

"OldOS started as an app designed to rebuild iOS 4 for modern devices in SwiftUI. It has evolved into an endeavor determined to preserve works of the past and educate on modern technologies."

**Comment by x13-me** [comment]
> FYI This is old OS:
> 
> https://www.oldos.dev/
> 
> About:
> 
> "OldOS started as an app designed to rebuild iOS 4 for modern devices in SwiftUI. It has evolved into an endeavor determined to preserve works of the past and educate on modern technologies."

If that app is what was being referenced, then no, there is no testflight available, it is not published to the store, and would be unlikely to pass initial checks if anyone attempted.

It is trivial to build for anyone that is interested, and a release is published at [The-OldOS-Project/releases](https://github.com/zzanehip/The-OldOS-Project/releases/latest) however support for this is out of scope for this project
