### ISSUE TITLE
Column order

### ISSUE THREAD

**Issue by TylerDKnight** [pluwen/awesome-testflight-link#127]
ReadMe table is too wide on mobile viewport because of the TestFlight links. Mobile browsers and the native GitHub app don't scale-to-fit the table even in landscape mode. This makes it difficult on mobile to see the name of the app and it's invite status at the same time. Suggesting changing the column order so that the link is not second. Or, if this could cause compatibility issues, then **formatting** the app name based on _status_.

**Comment by Freedox6** [comment]
Text @revised on instagram he can help or text me @opzy on ig I can help cause he told me how to do it to
