### ISSUE TITLE
Add soul knight prequal

### ISSUE THREAD

**Issue by Pikachupikachup** [pluwen/awesome-testflight-link#131]
It’s a game so put to there. Also thank you for all of your (hard?) work on this project, I use it all of the time!

**Comment by x13-me** [comment]
> It’s a game so put to there. Also thank you for all of your (hard?) work on this project, I use it all of the time!

Do you have the link?

**Comment by Pikachupikachup** [comment]
No, I can access taptap.io bc of a screen time limit(website limit)
