### ISSUE TITLE
Add my physique (iOS and macOS)

### ISSUE THREAD

**Issue by auroralia** [pluwen/awesome-testflight-link#150]
https://testflight.apple.com/join/BScDI9fh - AI powered fitness coach

https://www.reddit.com/r/TestFlight/comments/14h2kd7/recruiting_get_your_own_personal_trainer_powered/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

**Comment by pluwen** [comment]
done
