### ISSUE TITLE
Add Wars of Wanon (iOS)

### ISSUE THREAD

**Issue by RawiSoft** [pluwen/awesome-testflight-link#151]
Beta download: https://testflight.apple.com/join/UZ4tYFb6

 In this game, you'll battle hordes of aliens, collect powerful parts to upgrade your ships and weapons, and explore the vast space near the fictional planet of Wanon

Reddit post: https://www.reddit.com/r/TestFlight/comments/14o0rhx/recruiting_wars_of_wanon_ios_space_shooter_game/

**Comment by pluwen** [comment]
done

**Comment by RawiSoft** [comment]
Thank you so much

**Comment by pluwen** [comment]
IMP
