### ISSUE TITLE
App that converts speech into clear, structured text

### ISSUE THREAD

**Issue by iilfat** [pluwen/awesome-testflight-link#169]
Hello!
My app is called Letterly. It makes a great structured text from any speech.
You can try it on TestFlight: https://testflight.apple.com/join/cXnx4zVm
You feedback would be really valuable!

And if you want to join the waitlist to get the app as it is released, pleaase leave email here: https://forms.gle/d2kCm8aHMuMRVXgx9

Thank you in advance guys!

**Comment by pluwen** [comment]
done

**Comment by iilfat** [comment]
wow, so fast, thank you :)
