### ISSUE TITLE
App to take selfies with a gesture controls such as thumbs-up or peace signs

### ISSUE THREAD

**Issue by Rulik-Tech** [pluwen/awesome-testflight-link#173]
Hello!
My app is called RulikSelfie.
With its simple gesture controls and smile detection, you can take amazing selfies without touching your phone.
You can try it on TestFlight: 
https://testflight.apple.com/join/kID8pcDh

Your feedback would be really valuable!

Thank you in advance!

**Comment by pluwen** [comment]
done
