### ISSUE TITLE
3 iOS App Testflight links for Lua, Love2D and Solar2D(CoronaSDK)

### ISSUE THREAD

**Issue by andy380743909** [pluwen/awesome-testflight-link#221]
LuaLu REPL: https://testflight.apple.com/join/G2F9P9Nh

Love2D Game Maker: https://testflight.apple.com/join/bCLmQKfQ

Solar2d Studio: https://testflight.apple.com/join/QuRAxS6F

**Comment by pluwen** [comment]
Added Love2D Game Maker
done.
