### ISSUE TITLE
Tuttii - Real-Time Remixing / Mashup App

### ISSUE THREAD

**Issue by chonkums** [pluwen/awesome-testflight-link#224]
Tuttii is a new way to DJ / produce music through a novel drag & drop interface, no skill required. Play with song stem segments, tweak the speed and pitch of your remix, and share directly to UGC platforms. We handle all of the complexities of music production so you can simply create.

Feel free to request new music to be added while we work on our commercial licensing agreements ahead of our full launch. We'd appreciate any feedback, suggestions, or ideas while we're building!

https://testflight.apple.com/join/2dTbntXZ

**Comment by pluwen** [comment]
done
