### ISSUE TITLE
Add A TestFilght Link 沒有 Run workflow 選項

### ISSUE THREAD

**Issue by JC-Chung** [pluwen/awesome-testflight-link#54]
[Add A TestFilght Link](https://github.com/pluwen/awesome-testflight-link/actions/workflows/add_link.yml) 沒有 `Run workflow` 選項
而將 [awesome-testflight-link](https://github.com/pluwen/awesome-testflight-link) fork 到自己的 repositories 有出現選項，但執行後 main 被 [skipped](https://github.com/JC-Chung/awesome-testflight-link/runs/6181127289?check_suite_focus=true)

要添加的為 [Anubis - API Debug & Inspect](https://testflight.apple.com/join/LzjySbQx) - ios

**Comment by pluwen** [comment]
done
