### ISSUE TITLE
Update suggestions

### ISSUE THREAD

**Issue by Shiaulis** [pluwen/awesome-testflight-link#72]
At least several apps are accepting testers:
* github
* notion
* trello

Todoist link seems disabled so probably can be removed

Day One Journal status should be F, not N

I do understand that there is some automation under the hood for this repo so it is pointless to make changes in Readme. Am I right?

**Comment by tom-snow** [comment]
> I do understand that there is some automation under the hood for this repo so it is pointless to make changes in Readme. Am I right?

Sure! Make changes in Readme is pointless.

**Comment by tom-snow** [comment]
> At least several apps are accepting testers:
> 
> * github
> * notion
> * trello
> 
> Todoist link seems disabled so probably can be removed
> 
> Day One Journal status should be F, not N

From [Github Action Log](https://github.com/pluwen/awesome-testflight-link/actions/runs/3110441631/jobs/5041630817#step:6:10) you can find that lots of requests( to check status) been blocked. So the automatic program can't get the truly status of TestFlight link.

I'll try to adjustment the 'request interval'.

**Comment by tom-snow** [comment]
我将不再跟进这个项目，祝大家好运。

**Comment by pluwen** [comment]
@tom-snow 出现了很多错误

**Comment by tom-snow** [comment]
![image](https://user-images.githubusercontent.com/79245287/194801973-df76286c-e096-48f8-81f4-41d16fd12340.png)

自己改小一点吧，都说了是并发请求量高了。还不行的话你就把异步改成同步吧
